config/routes.rb
Rails.application.routes.draw do
  devise_for :users, modules: "users"
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  namespace :admins do
    resources :dashboards
    resources :offers
    resources :seeks
    resources :adverts
    # logs
    get 'departurelog', to: 'adverts#departurelog', as: 'adverts_departurelog'
    get 'destinationlog', to: 'adverts#destinationlog', as: 'adverts_destinationlog'
  end

  resource :home, only: [:show]
  get 'agb_datenschutz', to: 'home#agbdatenschutz', as: 'home_agbdatenschutz'
  get 'impressum', to: 'home#impressum', as: 'home_impressum'
  get 'hitchiwas', to: 'home#explain', as: 'home_explain'
  get 'sitemap', to: 'home#sitemap', as: 'home_sitemap'

  get 'login', to: 'home#login', as: 'home_login'
  get 'logincheck', to: 'home#logincheck', as: 'logincheck'
  get 'konto', to: 'offers#overview', as: 'offers_overview'

  get 'mitfahrgelegenheiten', to: 'offers#all', as: 'offers_mitfahrgelegenheiten'
  get 'mitfahrgelegenheit/:id', to: 'offers#show', as: 'offers_mitfahrgelegenheit'
  get 'mitfahrgelegenheit/:offer_id/anschreiben', to: 'messages#new', as: 'offers_new_message'
  get 'mitfahrgelegenheit/:id/bearbeiten', to: 'offers#edit', as: 'edit_offer_mitfahrgelegenheit'
  get 'neu', to: 'offers#new', as: 'neu'
  get 'suchen', to: 'offers#search', as: 'offers_search'
  get 'finden', to: 'offers#find', as: 'offers_find'

  get 'nachricht/:id/gelesen', to: 'messages#markread', as: 'markread'
  get 'nachricht/:offerid', to: 'offers#msglinkout', as: 'offers_msglinkout'
  get 'message_counter', to: 'offers#get_messagecount', as: 'message_counter'
  resources :messages do
    resources :answers
  end

  get 'adclick/:id', to: 'offers#adclick', as: 'adclick'
  resources :offers do
    get :autocomplete_cityname_name, :on => :collection
  end
  get 'weiterleitung/:offerid/:facebookid', to: 'offers#linkout', as: 'offers_linkout'

  root to: "home#show"
end

app/controllers/admins/offers_controller.rb
class Admins::OffersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admin_offer, only: [:show, :edit, :update, :destroy]
  before_action :sameadmin, only: [:show, :edit, :update, :destroy]
  before_action :user_logout

  # GET /admin_offers
  # GET /admin_offers.json
  def index
    @admin_offers = Offer.where(active: true, seek: false)
  end

  # GET /admin_offers/1
  # GET /admin_offers/1.json
  def show
  end

  # GET /admin_offers/new
  # def new
  #   @admin_offer = Offer.new
  # end

  # GET /admin_offers/1/edit
  def edit
  end

  # POST /admin_offers
  # POST /admin_offers.json
  # def create
  #   @admin_offer = Offer.new(admin_offer_params)
  #
  #   respond_to do |format|
  #     if @admin_offer.save
  #       format.html { redirect_to @admin_offer, notice: 'Admin offer was successfully created.' }
  #       format.json { render :show, status: :created, location: @admin_offer }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @admin_offer.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /admin_offers/1
  # PATCH/PUT /admin_offers/1.json
  def update
    respond_to do |format|
      if @admin_offer.update(admins_offer_params)
        format.html { redirect_to edit_admin_offer_path(@admin_offer), notice: 'Admin offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_offer }
      else
        format.html { render :edit }
        format.json { render json: @admin_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_offers/1
  # DELETE /admin_offers/1.json
  def destroy
    @admin_offer.destroy
    respond_to do |format|
      format.html { redirect_to admins_offers_url, notice: 'Admin offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_offer
      @admin_offer = Offer.find(params[:id])
    end

    def sameadmin
      if current_admin.id != 1 #1
        if @advert.admin_id != current_admin.id #2
          redirect_to admins_adverts_path, notice: "Das solltest du nicht tun!"
        end #eo2
        return true
      end #eo1
    end

    def user_logout
      if session[:user_id] != nil
        session[:user_id] = nil
        session[:expires_at] = Time.now
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_offer_params
      params.require(:offer).permit(:departurelocal, :departuredate, :departuretime, :destinationlocal, :description, :between_stops, :seek, :active, :rules, :departure_id, :destination_id)
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:overview, :new, :create, :get_messagecount]

  around_action :catch_not_found
  # security
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  before_action :max_offers, only: [:new, :create]
  # define the searchresults per page
  before_action :searchresultspp, only: [:search, :find]

  # autocomplete live query support via autocomplete gem
  autocomplete :cityname, :name, :full => true

  # GET /offers
  # GET /offers.json
  def index
    redirect_to root_path
  end

  def get_messagecount
    # pure json output for the ajax call in a jquery function (messagecount in navigation)
    respond_to do |format|
      format.json do
        posts = message_counter # message_counter is a global helper_method in ApplicationController
        data = posts
        render(json: data)
      end
    end
  end

  def all
    @offers = Offer.where(active: true)
  end

  def linkout
    # linkout for showing the facebook profile
    @offer = Offer.find(params[:offerid])
    @offer.increment!(:clickcounter, 1) if current_user && @offer.user_id != current_user.id
    @advert = Advert.where(city: @offer.destinationlocal).where("begin_ad <= ?", Date.today).where("end_ad >= ?", Date.today).order(viewcounter: :asc).first
    @advert.increment!(:viewcounter, 1) if @advert
  end

  def msglinkout
    # linkout when creating new message
    @offer = Offer.find(params[:offerid])
    @offer.increment!(:clickcounter, 1) if current_user && @offer.user_id != current_user.id
    @advert = Advert.where(city: @offer.destinationlocal).where("begin_ad <= ?", Date.today).where("end_ad >= ?", Date.today).order(viewcounter: :asc).first
    @advert.increment!(:viewcounter, 1) if @advert
  end

  def adclick
    # this is run when an app is clicked
    @advert = Advert.find(params[:id])
    @advert.increment!(:clickcounter, 1)
    redirect_to @advert.linkurl
  end

  def overview
    # destroy all offers with departuredate in the past
    if current_user
      @lateoffers = current_user.offers.where("departuredate < ?", Date.today)
      @lateoffers.each { |lateoffer| lateoffer.destroy } if @lateoffers
      @offers = current_user.offers.where(active: true).order(departuredate: :asc)
      # matching queries run in the view for proper alignment
      # _overview_offers and _overview_seek
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @departure = Departure.find(@offer.departure_id)
    @destination = Destination.find(@offer.destination_id)
    @depcoords = @departure.latitude.to_s + "," + @departure.longitude.to_s
    @destcoords = @destination.latitude.to_s + "," + @destination.longitude.to_s
    @offeruser = User.find(@offer.user_id)
    @offer.increment!(:viewcounter, 1) unless current_user && @offer.user_id == current_user.id
  end

  def search
    check_date_params("search") # sets @searchdate
    if params[:fahrtsuche].present? || params[:zielsuche].present?
      search = OffersSearch.new(@searchdate, params[:fahrtsuche], params[:zielsuche], show_seeks=false)
      offers = search.offers
      def pagy_get_items(array, pagy)
        array[pagy.offset, pagy.items]
      end
      @pagy, @offers = pagy(offers)
    else # only on empty search
      @searchdate = Date.today
      offer_count = Offer.where(active: true, seek: false).size
      case
      when offer_count > 3
        @offers = Offer.where(active: true, seek: false).sample(4)
      when offer_count > 1
        @offers = Offer.where(active: true, seek: false).sample(2)
      when offer_count == 1
        @offers = Offer.where(active: true, seek: false).sample(1)
      end
    end
  end #search

  def find
    check_date_params("find")
    if params[:fahrtsuche].present? || params[:zielsuche].present?
      search = OffersSearch.new(@searchdate, params[:fahrtsuche], params[:zielsuche], show_seeks=true)
      offers = search.offers
      def pagy_get_items(array, pagy)
        array[pagy.offset, pagy.items]
      end
      @pagy, @offers = pagy(offers)
    end
  end #end of find

  # GET /offers/new
  def new
    @offer = User.find(current_user.id).offers.build()
    @offer.departuredate = Date.today
  end

  # GET /offers/1/edit
  def edit
    # user permission checked via before_action hook
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = current_user.offers.build(offer_params)
    @offer.destinationlocal = @offer.destinationlocal.squish
    @offer.departurelocal = @offer.departurelocal.squish
    @offer.destination_id = Destination.find_or_create_by(name: @offer.destinationlocal).id
    @offer.departure_id = Departure.find_or_create_by(name: @offer.departurelocal).id

    Destination.find(@offer.destination_id).touch
    Departure.find(@offer.departure_id).touch
    @offer.active = true
    @deletedate = @offer.departuredate + 1.days

    if @offer.seek == true
      @offer.between_stops = ""
    else
      @offer.seek = false
      @offer.emailnotification = false
    end

    def send_mail_to_seeks
      @seeksusers = Offer.where(seek: true, active: true, emailnotification: true, departuredate: @offer.departuredate, departurelocal: @offer.departurelocal, destinationlocal: @offer.destinationlocal).pluck(:user_id)
      @users = User.where(id: @seeksusers).where.not(id: current_user.id)
      if @seeksusers.any? && @users.any?
        @users.each do |user|
          next unless user.email
          UserMailer.notification_email(user, @offer).deliver_now
        end
      end
    end

    respond_to do |format|
      if @offer.save
        send_mail_to_seeks if @offer.seek == false # only send mails if created offer is not a seek
        format.html { redirect_to offers_mitfahrgelegenheit_path(@offer), notice: 'Erfolgreich gespeichert! Dein hitchi wird am ' + @deletedate.strftime("%d.%m.%Y").to_s + " automatisch wieder gelöscht werden." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    # user permission checked via before_action hook
    attributes = offer_params.clone

    respond_to do |format|
      @offer.destination_id = Destination.find_or_create_by(name: attributes[:destinationlocal].squish).id
      @offer.departure_id = Departure.find_or_create_by(name: attributes[:departurelocal].squish).id
      Destination.find(@offer.destination_id).touch
      Departure.find(@offer.departure_id).touch
      if @offer.update(offer_params)

        @offer.update(between_stops: "") if @offer.seek == true
        @offer.update(seek: false, emailnotification: false) unless @offer.seek == true

        format.html { redirect_to offers_mitfahrgelegenheit_path(@offer, facebook_refresh: true), notice: 'Änderungen gespeichert.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    # user permission checked via before_action hook
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_overview_path, notice: 'Deine Anzeige wurde gelöscht.' }
      format.json { head :no_content }
    end
  end


  private

    def check_date_params(str)
      begin
        @searchdate = params[:datumsuche].to_date if params[:datumsuche]
        @searchdate = params[:mysuche].to_date if params[:mysuche]
      rescue NoMethodError
        redirect_to offers_search_path if str == "search"
        redirect_to offers_find_path if str == "find"
        return
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    def max_offers
      if current_user.offers.pluck(:id).count >= 6
        redirect_to offers_overview_path, notice: "Das geht leider nicht, Du kannst maximal 6 hitchis erstellen."
      end
    end

    def searchresultspp
      @searchresultspp = 8
    end
    def description=(value)
      self[:description] = value.to_s.squish
    end
    def departuretime=(value)
      self[:departuretime] = value.to_s.squish
    end

    def catch_not_found
      yield
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, :flash => { :error => "Diese Anzeige ist leider nicht mehr gültig. Bitte nutze die Suche :)" }
      return
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(
      :departurelocal,
      :departuredate,
      :departuretime,
      :destinationlocal,
      :description,
      :between_stops,
      :seek,
      :active,
      :rules,
      :user_id,
      :departure_id,
      :destination_id,
      :emailnotification
      )
    end
end

app/helpers/offers_helper.rb
module OffersHelper
  include Pagy::Frontend

  # Pagys::I18N.load(file: Rails.root.join('config', 'locales', 'de.yml'), language:'de')

  # Pagination for bootstrap: it returns the html with the series of links to the pages
  def pagy_nav_bootstrap(pagy)
    html, link, p_prev, p_next = +'', pagy_link_proc(pagy, 'class="page-link"'), pagy.prev, pagy.next

    html << (p_prev ? %(<li class="page-item prev">#{link.call p_prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"'}</li>)
                    : %(<li class="page-item prev disabled"><a href="#" class="page-link">#{pagy_t('pagy.nav.prev')}</a></li>))
    pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36]
      html << if    item.is_a?(Integer); %(<li class="page-item">#{link.call item}</li>)                                                               # page link
              elsif item.is_a?(String) ; %(<li class="page-item active">#{link.call item}</li>)                                                        # active page
              elsif item == :gap       ; %(<li class="page-item gap disabled"><a href="#" class="page-link">#{pagy_t('pagy.nav.gap')}</a></li>) # page gap
              end
    end
    html << (p_next ? %(<li class="page-item next">#{link.call p_next, pagy_t('pagy.nav.next'), 'aria-label="next"'}</li>)
                    : %(<li class="page-item next disabled"><a href="#" class="page-link">#{pagy_t('pagy.nav.next')}</a></li>))
    %(<nav class="pagy-nav-bootstrap pagination" role="navigation" aria-label="pager"><ul class="pagination">#{html}</ul></nav>)
  end
end

app/views/admins/offers/_form.html.erb
<hr>
<%= form_for(@admin_offer, :url => admin_offer_path(@admin_offer)) do |f| %>
<% if @admin_offer.errors.any? %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div id="error_explanation">
            <!-- <h2><%= @offer.errors.count %>
                Fehler sind noch zu beheben:</h2> -->
            <ul>
                <% @admin_offer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>
<% end # of errors %>
<div class="row">
    <div class="col-md-3 col-md-offset-3">
        <div class="field form-group">
            <%= f.label :departurelocal, 'Abfahrtsort' %><br>
            <%= f.text_field :departurelocal, class: "form-control" %>
        </div>
    </div>
    <div class="col-md-3">
        <div class="fiel form-group">
            <%= f.label :destinationlocal, 'Zielort' %><br>
            <%= f.text_field :destinationlocal, class: "form-control" %>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3 col-md-offset-3">
        <div class="fiel form-group">
            <%= f.label :departuredate, 'Datum <small>(maximal 6 Monate im Voraus)</small>'.html_safe %><br>
            <%= f.date_select :departuredate, start_year: Date.today.year, end_year: (Date.today + 6.months).year, class: "form-control" %>
        </div>
    </div>
    <div class="col-md-3">
        <div class="fiel form-group">
            <%= f.label :departuretime, 'Uhrzeit' %><br>
            <%= f.text_field :departuretime, class: "form-control" %>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="fiel form-group">
            <%= f.label :description, 'Zusätzliche Angaben (140 Zeichen)' %><br>
            <%= f.text_area :description, class: "form-control", maxlength: '140' %>
        </div>
    </div>
</div>

<div class="row between_stops">
  <div class="col-md-6 col-md-offset-3">
      <div class="fiel form-group">
          <%= f.label :between_stops, 'Zwischenstopps (getrennt durch Kommas, nach Abfolge auf Strecke geordnet)' %><br>
          <%= f.text_field :between_stops, class: "form-control" %>
      </div>
  </div>
</div>

<div class="row">
    <div class="col-md-3 col-md-offset-3">
        <div class="field form-group checkbox">
            <%= f.label :seek do %>
              <%= f.check_box :seek, class: "checkbox text-right" %>als Gesuch speichern
            <% end %>
        </div>
    </div>
    <div class="col-md-3">
        <% if f.object.persisted? %>
        <div class="field form-group checkbox">
            <%= f.label :active do %>
            <%= f.check_box :active, class: "checkbox text-right" %>aktiv
            <% end %>
        </div>
        <% end %>
    </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <div class="field form-group checkbox">
          <%= f.label :rules do %>
            <%= f.check_box :rules, class: "checkbox text-right" %>Ich erkläre mich mit den <%= link_to 'Allgemeinen Geschäftsbedingungen', home_agbdatenschutz_path, target: "_blank" %> sowie den <%= link_to 'Datenschutzbestimmungen', home_agbdatenschutz_path, target: "_blank" %> von hitchi.de einverstanden.
          <% end %>
      </div>
  </div>
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="actions">
            <%= link_to 'zurück', admin_dashboards_path, class: "btn btn-danger pull-left" %>
            <%= f.submit 'Fahrt speichern', class: "btn btn-success pull-right", id: "offersubmitbutton" %>
        </div>
    </div>
</div>
<% end %>

app/views/admins/offers/edit.html.erb
<h1>Editing Admin Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_offer %> |
<%= link_to 'Back', admins_offers_path %>

app/views/admins/offers/index.html.erb
<div class="row">
  <div class="col-xs-12">
<h1>Übersicht der aktiven Angebote</h1>

<table id="adTable" class="table table-striped tablesorter">
  <thead>
    <tr>
      <th>Startort</th>
      <th>Zielort</th>
      <th>Datum</th>
      <th>Uhrzeit</th>
      <th>Beschreibung</th>
      <th>Zwischenstopps</th>
      <th>Clicks</th>
      <th>Views</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_offers.each do |offer| %>
      <tr>
        <td><%= offer.departurelocal %></td>
        <td><%= offer.destinationlocal %></td>
        <td><%= offer.departuredate %></td>
        <td><%= offer.departuretime %></td>
        <td><%= offer.description %></td>
        <td><%= offer.between_stops %></td>
        <td><%= offer.clickcounter %></td>
        <td><%= offer.viewcounter %></td>
        <td><%= link_to 'anzeigen', offer %></td>
        <td><%= link_to 'bearbeiten', edit_admins_offer_path(offer) %></td>
        <td><%= link_to 'löschen', admins_offer_path(offer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- pager -->
<div id="pager" class="ts-pager">
  <form>
    <span class="first"><%= fa_icon("fast-backward") %></span>
    <span class="prev"><%= fa_icon("backward") %></span>
    <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
    <span class="next"><%= fa_icon("forward") %></span>
    <span class="last"><%= fa_icon("fast-forward") %></span>
    <select class="pagesize">
      <option value="10">10</option>
      <option value="20">20</option>
      <option value="30">30</option>
      <option value="40">40</option>
      <option value="all">Alle Zeilen</option>
    </select>
  </form>
</div>
<br>

</div>
</div>
<%= link_to 'Admin Dashbaord', admins_dashboards_path, class: "btn btn-danger" %>

<hr>
<% if admin_signed_in? %>
   <%= link_to('logout', destroy_admin_session_path, method: :delete, class: "btn btn-info") %>
<% end %>

app/views/admins/offers/new.html.erb
<h1>New Admin Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_offers_path %>

app/views/admins/offers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_offer_path(@admin_offer) %> |
<%= link_to 'Back', admins_offers_path %>