config/routes.rb
Rails.application.routes.draw do
  devise_for :users, modules: "users"
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }

  namespace :admins do
    resources :dashboards
    resources :offers
    resources :seeks
    resources :adverts
    # logs
    get 'departurelog', to: 'adverts#departurelog', as: 'adverts_departurelog'
    get 'destinationlog', to: 'adverts#destinationlog', as: 'adverts_destinationlog'
  end

  resource :home, only: [:show]
  get 'agb_datenschutz', to: 'home#agbdatenschutz', as: 'home_agbdatenschutz'
  get 'impressum', to: 'home#impressum', as: 'home_impressum'
  get 'hitchiwas', to: 'home#explain', as: 'home_explain'
  get 'sitemap', to: 'home#sitemap', as: 'home_sitemap'

  get 'login', to: 'home#login', as: 'home_login'
  get 'logincheck', to: 'home#logincheck', as: 'logincheck'
  get 'konto', to: 'offers#overview', as: 'offers_overview'

  get 'mitfahrgelegenheiten', to: 'offers#all', as: 'offers_mitfahrgelegenheiten'
  get 'mitfahrgelegenheit/:id', to: 'offers#show', as: 'offers_mitfahrgelegenheit'
  get 'mitfahrgelegenheit/:offer_id/anschreiben', to: 'messages#new', as: 'offers_new_message'
  get 'mitfahrgelegenheit/:id/bearbeiten', to: 'offers#edit', as: 'edit_offer_mitfahrgelegenheit'
  get 'neu', to: 'offers#new', as: 'neu'
  get 'suchen', to: 'offers#search', as: 'offers_search'
  get 'finden', to: 'offers#find', as: 'offers_find'

  get 'nachricht/:id/gelesen', to: 'messages#markread', as: 'markread'
  get 'nachricht/:offerid', to: 'offers#msglinkout', as: 'offers_msglinkout'
  get 'message_counter', to: 'offers#get_messagecount', as: 'message_counter'
  resources :messages do
    resources :answers
  end

  get 'adclick/:id', to: 'offers#adclick', as: 'adclick'
  resources :offers do
    get :autocomplete_cityname_name, :on => :collection
  end
  get 'weiterleitung/:offerid/:facebookid', to: 'offers#linkout', as: 'offers_linkout'

  root to: "home#show"
end

app/controllers/admin_dashboards_controller.rb
class AdminDashboardsController < ApplicationController
  before_action :authenticate_admin!
  before_action :user_logout
  before_action :set_admin_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /admin_dashboards
  # GET /admin_dashboards.json
  def index
    #@admin_dashboards = AdminDashboard.all
    @userscount = User.pluck(:id).count
    @messagescount = Message.pluck(:id).count
    @answerscount = Answer.pluck(:id).count
    @offerscount = Offer.pluck(:id).count
  end

  def matches

  end # of matches

  # GET /admin_dashboards/1
  # GET /admin_dashboards/1.json
  def show
  end

  # GET /admin_dashboards/new
  def new
    #@admin_dashboard = AdminDashboard.new
  end

  # GET /admin_dashboards/1/edit
  def edit
  end

  # POST /admin_dashboards
  # POST /admin_dashboards.json
  def create
    @admin_dashboard = AdminDashboard.new(admin_dashboard_params)

    respond_to do |format|
      if @admin_dashboard.save
        format.html { redirect_to @admin_dashboard, notice: 'Admin dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @admin_dashboard }
      else
        format.html { render :new }
        format.json { render json: @admin_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_dashboards/1
  # PATCH/PUT /admin_dashboards/1.json
  def update
    respond_to do |format|
      if @admin_dashboard.update(admin_dashboard_params)
        format.html { redirect_to @admin_dashboard, notice: 'Admin dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_dashboard }
      else
        format.html { render :edit }
        format.json { render json: @admin_dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_dashboards/1
  # DELETE /admin_dashboards/1.json
  def destroy
    @admin_dashboard.destroy

    respond_to do |format|
      format.html { redirect_to admin_dashboards_url, notice: 'Admin dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_dashboard
      @admin_dashboard = AdminDashboard.find(params[:id])
    end

    def user_logout
      if session[:user_id] != nil
        session[:user_id] = nil
        session[:expires_at] = Time.now
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_dashboard_params
      params.require(:admin_dashboard).permit(:index)
    end
end

app/helpers/admin_dashboards_helper.rb
module AdminDashboardsHelper
end

app/views/admin_dashboards/edit.html.erb
<h1>Editing Admin Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_dashboard %> |
<%= link_to 'Back', admin_dashboards_path %>

app/views/admin_dashboards/index.html.erb
<br>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <p><%#= link_to 'Werbung verwalten',adverts_path %></p>
        <p><%= link_to 'Mitfahrgelegenheiten verwalten', admin_offers_path %></p>
        <p><%= link_to 'Mitfahrgesuche verwalten', admin_seeks_path %></p>
        <p><%= link_to 'Abfahrtsort auswerten', adverts_departurelog_path %></p>
        <p><%= link_to 'Zielorte auswerten', adverts_destinationlog_path %></p>
        <hr class="hroffersplit">
        <p>
            <strong>User mit Login:</strong>
            <%= @userscount %></p>
        <p>
            <strong>Anzeigen aktuell:</strong>
            <%= @offerscount %></p>
        <p>
            <strong>Nachrichten / Anworten:</strong>
            <%= @messagescount %>
            /
            <%= @answerscount %></p>
        <hr class="hroffersplit">
        <% if admin_signed_in? %>
        <%= link_to('logout', destroy_admin_session_path, method: :delete, class: "btn btn-info") %>
        <% end %>
    </div>
</div>

app/views/admin_dashboards/new.html.erb
<h1>New Admin Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_dashboards_path %>

app/views/admin_dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @admin_dashboard.index %>
</p>

<%= link_to 'Edit', edit_admin_dashboard_path(@admin_dashboard) %> |
<%= link_to 'Back', admin_dashboards_path %>